-- Active: 1773133692328@@127.0.0.1@3306
USE customer_behaviour;

SELECT *
FROM customer_shopping
LIMIT 10;

SHOW TABLES;

-- Q1. What is the total revenue generated by male versus female customers?
 
SELECT gender, SUM(purchase_amount) AS total_purchase_amount
FROM customer_shopping
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT 
	customer_id , purchase_amount
FROM customer_shopping
WHERE 
	discount_applied = "Yes" AND
    purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_shopping);
    
-- Q3. Which are the top 5 products with the highest average review rating?

SELECT 
	item_purchased , ROUND(AVG(review_rating) , 2) as AVG_Review_Rating
FROM customer_shopping
GROUP BY item_purchased
ORDER BY AVG_Review_Rating desc
limit 5 ;

-- Q4. Compare the average purchase amount between standard and express shipping.

SELECT 
    shipping_type,
    AVG(purchase_amount) AS avg_purchase
FROM customer_shopping
WHERE shipping_type in ('Standard' , 'Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more than non-subscribed customers? (Compare average spend and total revenue between subscribers and non-subscribers)

SELECT 
    subscription_status ,
    AVG(purchase_amount) AS avg_purchase ,
    SUM(purchase_amount) AS total_amount
FROM customer_shopping
WHERE subscription_status in ('Yes' , 'No')
GROUP BY subscription_status;

-- Q6. Which five products have the highest percentage of purchases with discounts applied? (Calculate discount rate per product)

SELECT 
    item_purchased,
    COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) AS discounted_purchases,
    ROUND(
        (100 * COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) / COUNT(*)),
        2
    ) AS percentage_of_discounts
FROM customer_shopping
GROUP BY item_purchased
ORDER BY percentage_of_discounts DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment .(New = 1 purchase | Returning = 2-10 purchases | Loyal = more than 10 purchases)

SELECT 
    COUNT(*) as customer_count,
    CASE
				WHEN previous_purchases = 1 THEN "NEW" 
                WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
                WHEN previous_purchases > 10 THEN "Loyal"
	END as Customers_loyalty
FROM customer_shopping
GROUP BY Customers_loyalty ;

-- Q8. What are the top 3 most purchased products within each category? (Use a window function to rank products by total orders within each category)

WITH CTE AS (
    SELECT 
        category,
        item_purchased,
        COUNT(item_purchased) AS counting_of_item_purchased,
        RANK() OVER (
            PARTITION BY category 
            ORDER BY COUNT(item_purchased) DESC
        ) AS Ranking_of_category
    FROM customer_shopping 
    GROUP BY category, item_purchased
)

SELECT * 
FROM CTE 
WHERE Ranking_of_category <= 3;


-- Q9. Are customers who are repeat buyers also likely to subscribe? (Repeat buyers = customers with more than 5 previous purchases)

SELECT 
    subscription_status,
    COUNT(*) AS repeat_buyers
FROM customer_shopping
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue by age group? (Order by total revenue in descending order)
 
 SELECT 
	age_group ,
    sum(purchase_amount) AS Total_revenue_by_age_group
FROM customer_shopping 
GROUP BY age_group 
ORDER BY Total_revenue_by_age_group DESC;